import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WebTabFooter from "@/components/WebTabFooter";
import { AuthProvider } from '@/contexts/AuthContext'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SHOPMARK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        {/* <Navbar/>  */}
        {children}

        <WebTabFooter />
        </AuthProvider>
      </body>
    </html>
  );
}
